### ISSUE TITLE
Migrate to JCOBridge 2.4.*

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KafkaBridge#2]
**Is your feature request related to a problem? Please describe.**
On November 8 .NET 6 was released. To use the latest version this project shall migrate to [JCOBridge 2.4.0](https://www.nuget.org/packages/MASES.JCOBridge/2.4.0)

**Describe the solution you'd like**
Upgrade project to target the new JCOBridge version

**Describe alternatives you've considered**
N/A

**Additional context**
#1 shall use the new features of the latest version of JCOBridge

**Comment by mariomastrodicasa** [comment]
@masesdevelopers add this snippet to the project containing reference on JCOBridge to propagate management of .targets:
```
	<PackageReference Include="MASES.JCOBridge" Version="2.4.6">
		<IncludeAssets>All</IncludeAssets>
		<PrivateAssets>None</PrivateAssets>
	</PackageReference>
```

**Comment by masesdevelopers** [comment]
> @masesdevelopers add this snippet to the project containing reference on JCOBridge to propagate management of .targets:
> 
> ```
> 	<PackageReference Include="MASES.JCOBridge" Version="2.4.6">
> 		<IncludeAssets>All</IncludeAssets>
> 		<PrivateAssets>None</PrivateAssets>
> 	</PackageReference>
> ```

Add in PR #22. Issue closed.
