### ISSUE TITLE
Integrates JavaBridge package

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KafkaBridge#46]
**Is your feature request related to a problem? Please describe.**
There are many Java classes now available in JavaBridge, remove this classes from KafkaBridge to have a clean implementation strictly related to Apache Kafka.

**Describe the solution you'd like**
Remove the classes from the repository and reference the JavaBridge package

**Describe alternatives you've considered**
No one

**Additional context**
No one

**Comment by masesdevelopers** [comment]
Now the package has renamed in JNet
