### ISSUE TITLE
Improve Stream classes

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KafkaBridge#7]
**Is your feature request related to a problem? Please describe.**
#3 does not cover all features available in the Java classes, the classes shall be enhanced

**Describe the solution you'd like**
Add more methods/fields on the classes involved to have a reach code base

**Describe alternatives you've considered**
N/A

**Additional context**
Related to #3

**Comment by masesdevelopers** [comment]
API covered. Issue will be closed.

**Comment by mariomastrodicasa** [comment]
The files shall be checked: this https://github.com/masesgroup/KafkaBridge/blob/45f22c90f5d7698c8c7815d989228a69c9a558a3/src/net/KafkaBridge/ClientSide/BridgedClasses/Streams/State/Stores.cs#L28 and some other are not correct.
